### ISSUE TITLE
Entities should not generate their document themself

### ISSUE THREAD

**Issue by Nek-** [monsieurbiz/SyliusSearchPlugin#46]
By design using this bundle, only entities can generate their own Document definition. This is not a so great idea for 2 reasons:
1. The schema should actually be static, dynamic schema generation from elasticsearch is not recommended (you should be able to learn why in some conference of Damien Alexandre x))
2. You may want to generate something different from only data coming from your model. And sometimes it can be complex (we have the issue with promotions). So in order to generate the document we need to call an external service but we are inside an entity.

We could imagine some fix where repositories return an object with the entity injected inside but that's not great and there's no interface inside the project that could help to do that.

Another eventual solution would be to decorate the indexer, but once again there's no interface so it leads to extension with private attributes... (I'm not team extension is evil, but if everything is private it's not that easy to extends) here again an interface could be great.

**Comment by jacquesbh** [comment]
Thank you @Nek- for your contribution!

We will indeed improve the plugin when possible and having a better way to define the indexed documents is something we should work on.
Especially because I totally agree with you: an entity should not be the document itself.

What do you think about using factories to provide the Documents? We could also use Proxies or Events to provide the flexibility you may need.

**Comment by Nek-** [comment]
Factories sounds the easy and logic solution. Especially considering it's the exact same pattern sylius uses internally for this kind of things.

**Comment by azambon** [comment]
I'm encoutering some trouble precisely because of this limitation: I would like to use some external services as part of the document generation code, but since everything is confined inside an entity, I cannot inject the external service(s) that I need.

As a temporary fix, perhaps it would be possible to pass the service container as a second argument in all calls to convertToDocument(). This way the code inside the entity would be able to access the needed services.

**Comment by maximehuran** [comment]
I think it's done in v2.
I let you open a new issue if it's not the case.
